// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Values taken verbatim from android/app/google-services.json
  // (project voltix-54e22, package cc.voltix.streaming).
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQvTY1LVd38pmxaWPMcOXlLp11UWD-xcU',
    appId: '1:292540273471:android:cc83292aa127b02194398a',
    messagingSenderId: '292540273471',
    projectId: 'voltix-54e22',
    storageBucket: 'voltix-54e22.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0bdm2kH6URX402ocSBahUsyvEVmyI5PA',
    appId: '1:292540273471:ios:adf3d2408172997e94398a',
    messagingSenderId: '292540273471',
    projectId: 'voltix-54e22',
    storageBucket: 'voltix-54e22.firebasestorage.app',
    iosBundleId: 'org.moonfin.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0bdm2kH6URX402ocSBahUsyvEVmyI5PA',
    appId: '1:292540273471:ios:adf3d2408172997e94398a',
    messagingSenderId: '292540273471',
    projectId: 'voltix-54e22',
    storageBucket: 'voltix-54e22.firebasestorage.app',
    iosBundleId: 'org.moonfin.app',
  );
}
